// routes.js or routes.ts
export const ROUTES = {
	HOME: "/",
	WELCOME: "/welcome",
	LOGIN: "/login",
	MENU: "/menu",
	PROFILE: "/creator-profile",
	FEED: "/feed",
	REGISTER: "/register",
	REQUEST_RESET_PASSWORD: "/request-reset-password",
	RESET_PASSWORD: "/reset-password",
	VERIFY_OTP: "/verify-otp",
	USER_DETAILS: "/user-details",
	CREATOR_SOCIALS: "/creator-socials",
	FINAL_STEP: "/final-step",
	PHOTO_SELECTOR: "/select-photo",
	DONE: "/done",
	PWD_SUCCESSFULLY_CHANGED: "/pwd-successfully-changed",
	NOT_FOUND: "*",
	LOGOUT: "/logout",
	PROMPT_MODAL: "/prompt-modal",
	IMAGE_SELECTION: "/image-selection",
};
